// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package lexer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EOF-0]
	_ = x[Plus-1]
	_ = x[Minus-2]
	_ = x[Times-3]
	_ = x[Divide-4]
	_ = x[Remainder-5]
	_ = x[And-6]
	_ = x[Or-7]
	_ = x[Caret-8]
	_ = x[Tilde-9]
	_ = x[Backtick-10]
	_ = x[SingleQuote-11]
	_ = x[LessThan-12]
	_ = x[GreaterThan-13]
	_ = x[Equals-14]
	_ = x[Colon-15]
	_ = x[Not-16]
	_ = x[Comma-17]
	_ = x[Period-18]
	_ = x[Semicolon-19]
	_ = x[LeftParen-20]
	_ = x[RightParen-21]
	_ = x[LeftBrace-22]
	_ = x[RightBrace-23]
	_ = x[LeftBracket-24]
	_ = x[RightBracket-25]
	_ = x[DollarSign-26]
	_ = x[QuestionMark-27]
	_ = x[LogicalAnd-28]
	_ = x[LogicalOr-29]
	_ = x[LeftShift-30]
	_ = x[RightShift-31]
	_ = x[LogicalEquals-32]
	_ = x[FatArrow-33]
	_ = x[NotEquals-34]
	_ = x[LessThanEquals-35]
	_ = x[GreaterThanEquals-36]
	_ = x[ColonEquals-37]
	_ = x[Exponentiation-38]
	_ = x[DotDot-39]
	_ = x[LeftArrow-40]
	_ = x[RightArrow-41]
	_ = x[Fun-42]
	_ = x[Type-43]
	_ = x[Trait-44]
	_ = x[Import-45]
	_ = x[Let-46]
	_ = x[Var-47]
	_ = x[If-48]
	_ = x[Else-49]
	_ = x[Case-50]
	_ = x[Match-51]
	_ = x[Package-52]
	_ = x[Iso-53]
	_ = x[Ref-54]
	_ = x[Mut-55]
	_ = x[Pub-56]
	_ = x[Ident-57]
	_ = x[Number-58]
	_ = x[Whitespace-59]
	_ = x[SingleLineComment-60]
	_ = x[StringBeg-61]
	_ = x[StringPart-62]
	_ = x[StringEnd-63]
	_ = x[String-64]
	_ = x[Illegal-65]
}

const _TokenType_name = "EOFPlusMinusTimesDivideRemainderAndOrCaretTildeBacktickSingleQuoteLessThanGreaterThanEqualsColonNotCommaPeriodSemicolonLeftParenRightParenLeftBraceRightBraceLeftBracketRightBracketDollarSignQuestionMarkLogicalAndLogicalOrLeftShiftRightShiftLogicalEqualsFatArrowNotEqualsLessThanEqualsGreaterThanEqualsColonEqualsExponentiationDotDotLeftArrowRightArrowFunTypeTraitImportLetVarIfElseCaseMatchPackageIsoRefMutPubIdentNumberWhitespaceSingleLineCommentStringBegStringPartStringEndStringIllegal"

var _TokenType_index = [...]uint16{0, 3, 7, 12, 17, 23, 32, 35, 37, 42, 47, 55, 66, 74, 85, 91, 96, 99, 104, 110, 119, 128, 138, 147, 157, 168, 180, 190, 202, 212, 221, 230, 240, 253, 261, 270, 284, 301, 312, 326, 332, 341, 351, 354, 358, 363, 369, 372, 375, 377, 381, 385, 390, 397, 400, 403, 406, 409, 414, 420, 430, 447, 456, 466, 475, 481, 488}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
