// Code generated by "stringer -type=Base"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Bool-0]
	_ = x[Int-1]
	_ = x[Int8-2]
	_ = x[Int16-3]
	_ = x[Int32-4]
	_ = x[Int64-5]
	_ = x[Uint-6]
	_ = x[Uint8-7]
	_ = x[Uint16-8]
	_ = x[Uint32-9]
	_ = x[Uint64-10]
	_ = x[Float32-11]
	_ = x[Float64-12]
	_ = x[String-13]
}

const _Base_name = "BoolIntInt8Int16Int32Int64UintUint8Uint16Uint32Uint64Float32Float64String"

var _Base_index = [...]uint8{0, 4, 7, 11, 16, 21, 26, 30, 35, 41, 47, 53, 60, 67, 73}

func (i Base) String() string {
	if i < 0 || i >= Base(len(_Base_index)-1) {
		return "Base(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Base_name[_Base_index[i]:_Base_index[i+1]]
}
